version: '3.8'
services: 
    web:
        build:
            context: .
        env_file: ./.env
        command: npm start
        volumes: 
            - .:/app/
            - /app/node_modules
        ports:
            - 4000:4000
        depends_on: 
            - mysqldb
        environment: 
            MYSQL_HOST: mysqldb
    mysqldb:
        image: mysql:8.0
        env_file: ./.env
        environment: 
            MYSQL_DATABASE: 'database'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'developer'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'developer'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'developer'
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config:
